apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processor
  labels:
    app: order-processor
spec:
  selector:
    matchLabels:
      app: order-processor
  template:
    metadata:
      labels:
        app: order-processor
    spec:
      containers:
      - name: order-processor
        image: tomkerkhove/keda-sample-dotnet-worker-servicebus-queue
        env:
        - name: KEDA_SERVICEBUS_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
             name: order-secrets
             key: SERVICEBUS_CONNECTIONSTRING
        - name: KEDA_SERVICEBUS_QUEUENAME
          value: orders
---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: order-processor-scaler
  labels:
    app: order-processor
    deploymentName: order-processor
spec:
  scaleTargetRef:
    deploymentName: order-processor
  # minReplicaCount: 0 Change to define how many minimum replicas you want
  maxReplicaCount: 10
  triggers:
  - type: azure-servicebus
    metadata:
      queueName: orders
      connection: KEDA_SERVICEBUS_CONNECTIONSTRING
      queueLength: '5'
---
apiVersion: v1
kind: Secret
metadata:
  name: order-secrets
  labels:
    app: order-processor
data:
  SERVICEBUS_CONNECTIONSTRING: RW5kcG9pbnQ9c2I6Ly9rZWRhLXNhbmRib3guc2VydmljZWJ1cy53aW5kb3dzLm5ldC87U2hhcmVkQWNjZXNzS2V5TmFtZT1Sb290TWFuYWdlU2hhcmVkQWNjZXNzS2V5O1NoYXJlZEFjY2Vzc0tleT1xTUNGTVhiSmVYempXbDVtbmlYdHBYWm8wUHk2QWRwRjJMNG04K2hhYXB3PQo=
  SERVICEBUS_QUEUE_CONNECTIONSTRING: RW5kcG9pbnQ9c2I6Ly9rZWRhLXNhbmRib3guc2VydmljZWJ1cy53aW5kb3dzLm5ldC87U2hhcmVkQWNjZXNzS2V5TmFtZT1RdWV1ZS1NYW5hZ2U7U2hhcmVkQWNjZXNzS2V5PVRMcXo4TTc5VElRUDBTS0JTSGdXMEFZSHk5NDEzcEkzUDgrWW8rNjNlVEk9O0VudGl0eVBhdGg9b3JkZXJzCg==