apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-web
  labels:
    app: order-web
spec:
  selector:
    matchLabels:
      app: order-web
  template:
    metadata:
      labels:
        app: order-web
    spec:
      containers:
      - name: order-web
        image: jakobehn/keda-samples-dotnet-web
        env:
        - name: KEDA_SERVICEBUS_QUEUE_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
             name: secrets-order-consumer
             key: servicebus-connectionstring
---
apiVersion: v1
kind: Service
metadata:
  name: kedasampleweb
  labels:
    app: order-web
spec:
  selector:
    app: order-web
  ports:
    - protocol: TCP
      port: 80
  type: LoadBalancer