apiVersion: keda.k8s.io/v1alpha1
kind: TriggerAuthentication
metadata:
  name: trigger-auth-service-bus-orders
spec:
  secretTargetRef:
  - parameter: connection
    name: secrets-order-management
    key: servicebus-order-management-connectionstring
---
apiVersion: v1
kind: Secret
metadata:
  name: secrets-order-management
  labels:
    app: order-processor
data:
  servicebus-order-management-connectionstring: RW5kcG9pbnQ9c2I6Ly9rZWRhc2Iuc2VydmljZWJ1cy53aW5kb3dzLm5ldC87U2hhcmVkQWNjZXNzS2V5TmFtZT1vcmRlci1jb25zdW1lcjtTaGFyZWRBY2Nlc3NLZXk9ckJZdzU3YkpqUFQ0QnFmZlg5SWxCTkU3OEJGM1VFejU0TTJjV0RsTjcyMD07RW50aXR5UGF0aD1vcmRlcnMK
---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: order-processor-scaler
  labels:
    app: order-processor
    deploymentName: order-processor
spec:
  scaleTargetRef:
    deploymentName: order-processor
  # minReplicaCount: 0 Change to define how many minimum replicas you want
  maxReplicaCount: 10
  triggers:
  - type: azure-servicebus
    metadata:
      queueName: orders
      queueLength: '5'
    authenticationRef:
      name: trigger-auth-service-bus-orders