apiVersion: v1
kind: Secret
metadata:
  name: order-secrets
  labels:
    app: order-processor
data:
  SERVICEBUS_QUEUE_CONNECTIONSTRING: RW5kcG9pbnQ9c2I6Ly9rZWRhLXNhbmRib3guc2VydmljZWJ1cy53aW5kb3dzLm5ldC87U2hhcmVkQWNjZXNzS2V5TmFtZT1RdWV1ZS1NYW5hZ2U7U2hhcmVkQWNjZXNzS2V5PVRMcXo4TTc5VElRUDBTS0JTSGdXMEFZSHk5NDEzcEkzUDgrWW8rNjNlVEk9O0VudGl0eVBhdGg9b3JkZXJzCg==