apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: trigger-auth-service-bus-orders
spec:
  secretTargetRef:
  - parameter: connection
    name: secrets-order-management
    key: servicebus-order-management-connectionstring
---
apiVersion: v1
kind: Secret
metadata:
  name: secrets-order-management
  labels:
    app: order-processor
data:
  servicebus-order-management-connectionstring: <base64-encoded-connection-string>
---
apiVersion: keda.sh/v1alpha1 
kind: ScaledObject
metadata:
  name: order-processor-scaler
spec:
  scaleTargetRef:
    name: order-processor
  minReplicaCount: 0 # Change to define how many minimum replicas you want
  maxReplicaCount: 50
  # The period to wait after the last trigger reported active before scaling the resource back to 0.
  # By default itâ€™s 5 minutes (300 seconds).
  cooldownPeriod: 5
  triggers:
  - type: azure-servicebus
    metadata:
      queueName: orders
      messageCount: '50'
    authenticationRef:
      name: trigger-auth-service-bus-orders